project:
  type: website
  output-dir: docs

website:
  title: "Bradford Johnson"
  navbar:
    left:
      - href: index.qmd
      - about.qmd
  page-footer:
    right: "This portfolio is built with ❤️ and [Quarto](https://quarto.org/)."
format:
  html:
    theme: Flatly
    css: styles.css
    toc: false

editor: visual

